services:
  postgres:
    image: postgres:16
    container_name: oj-postgres
    environment:
      POSTGRES_DB: oj
      POSTGRES_USER: ojuser
      POSTGRES_PASSWORD: DEV1226!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: oj-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
